name: Notify Parent Repository

on:
  push:
    branches: [ main ]
    paths:
      - '**/__meta__.txt'
      - '*/'
      - '**/*.md'
      - '**/*.json'
      - '**/*.yml'
      - '**/*.yaml'
  workflow_dispatch:

jobs:
  notify-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get commit information
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_SHA=$(git rev-parse HEAD)
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          
          COMMIT_MESSAGE_ESCAPED=$(echo "$COMMIT_MESSAGE" | sed 's/"/\\"/g' | sed "s/'/\\'/g")
          
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE_ESCAPED" >> $GITHUB_ENV
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV
          
          echo "📝 提交: $COMMIT_MESSAGE"
          echo "🔗 SHA: $COMMIT_SHA"

      - name: Trigger parent repository
        run: |
          TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          
          RESPONSE=$(curl -s -w "%{http_code}" -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PLAYBOOK_PLAYBOOK_DOOR }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/Space-tang/Playbook-Door/dispatches \
            -d "{
              \"event_type\": \"submodule-update\",
              \"client_payload\": {
                \"repository\": \"PlayBook\",
                \"ref\": \"main\",
                \"updated_at\": \"$TIMESTAMP\",
                \"commit_message\": \"$COMMIT_MESSAGE\",
                \"commit_sha\": \"$COMMIT_SHA\",
                \"commit_author\": \"$COMMIT_AUTHOR\",
                \"workflow_run_id\": \"${{ github.run_id }}\"
              }
            }")
          
          HTTP_CODE="${RESPONSE: -3}"
          
          if [ "$HTTP_CODE" -eq 204 ]; then
            echo "✅ 成功通知 Playbook-Door 仓库"
          else
            echo "❌ 通知失败 (HTTP $HTTP_CODE)"
            echo "响应: ${RESPONSE%???}"
            exit 1
          fi